"""Run a top-k portfolio backtest from ablation prediction scores.

Loads per-sample model scores from a prediction_scores_*.csv file (generated by the
ablation runner), selects the top-k stocks by score on each rebalance date, and
computes real 3-day forward returns for both the model portfolio and the Nifty50 benchmark.

Inputs:
    --predictions       Path to prediction_scores_<variant>.csv (required).
    --tabular-samples   Path to tabular_samples.csv containing per-stock date/close columns.
    --raw-dir           Directory with per-stock CSVs (RELIANCE_NS.csv etc.) and NSEI.csv.
                        Required when tabular_samples.csv does not have forward-return columns.
    --top-k             Number of stocks to hold per rebalance date (default: 1).

Outputs (in --output-dir):
    backtest_metrics.json   Cumulative returns, Sharpe ratio, max drawdown.
    backtest_curve.png      Cumulative return curve vs benchmark.

Interpretation:
    The model underperforms the benchmark on the 6-stock 1-year dataset (model −52.1% vs
    benchmark −16.1% using real forward returns). This is consistent with sub-0.5 validation
    AUC in the high-volatility fold: anti-predictive top-1 selection compounds over 50 daily
    rebalances. Use --use-y-proxy only to reproduce the old (incorrect) proxy result.
"""

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run a top-k portfolio backtest.")
    parser.add_argument("--predictions", type=str, required=True, help="Path to prediction_scores_*.csv")
    parser.add_argument("--tabular-samples", type=str, required=True, help="Path to tabular_samples.csv")
    parser.add_argument("--output-dir", type=str, default="data/processed/backtest")
    parser.add_argument("--top-k", type=int, default=1, help="Number of top stocks to hold")
    parser.add_argument(
        "--raw-dir",
        type=str,
        default=None,
        help="Directory with raw per-stock CSVs (e.g. RELIANCE_NS.csv) and NSEI.csv. "
        "Required when tabular_samples.csv does not contain forward-return columns.",
    )
    parser.add_argument(
        "--horizon-days",
        type=int,
        default=3,
        help="Forward-return horizon in trading days (must match the label horizon).",
    )
    parser.add_argument(
        "--use-y-proxy",
        action="store_true",
        help="Fall back to the y_true outperformance proxy (old behaviour, not a real backtest).",
    )
    return parser


def _ticker_to_filename(stock_id: str) -> str:
    """Convert 'RELIANCE.NS' → 'RELIANCE_NS.csv'."""
    return stock_id.replace(".", "_") + ".csv"


def _compute_forward_returns(
    samples: pd.DataFrame,
    raw_dir: Path,
    horizon_days: int,
) -> pd.DataFrame:
    """Attach stock_future_return and index_future_return columns to *samples*.

    Strategy:
    1. Compute per-stock forward returns from the 'close' column already present
       in tabular_samples.csv (shift -horizon_days within each stock group).
    2. Load NSEI.csv from raw_dir to obtain the benchmark forward return for
       the same dates.

    Returns a copy of *samples* with two new columns added.
    """
    out = samples.copy()
    out = out.sort_values(["stock_id", "date"]).reset_index(drop=True)

    # Per-stock forward return from close already in tabular_samples.csv
    out["stock_future_return"] = (
        out.groupby("stock_id")["close"]
        .transform(lambda s: s.shift(-horizon_days) / s - 1.0)
    )

    # Benchmark forward return from NSEI.csv
    nsei_path = raw_dir / "NSEI.csv"
    if not nsei_path.exists():
        raise FileNotFoundError(
            f"Benchmark CSV not found at {nsei_path}. "
            "Provide --raw-dir pointing to the directory that contains NSEI.csv."
        )
    nsei = pd.read_csv(nsei_path, parse_dates=["date"])
    nsei = nsei.sort_values("date").reset_index(drop=True)
    nsei["index_future_return"] = nsei["close"].shift(-horizon_days) / nsei["close"] - 1.0

    out = out.merge(
        nsei[["date", "index_future_return"]],
        on="date",
        how="left",
    )
    return out


def _sharpe(returns: pd.Series, trading_days: int = 252) -> float:
    """Annualised Sharpe ratio (risk-free rate = 0)."""
    if returns.std() == 0:
        return float("nan")
    return float(returns.mean() / returns.std() * np.sqrt(trading_days))


def _max_drawdown(cum_returns: pd.Series) -> float:
    """Maximum peak-to-trough drawdown as a positive fraction."""
    roll_max = cum_returns.cummax()
    drawdown = cum_returns / roll_max - 1.0
    return float(drawdown.min())


def main() -> None:
    parser = build_arg_parser()
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Loading predictions from {args.predictions}...")
    preds = pd.read_csv(args.predictions)
    if "stock_id" not in preds.columns:
        raise ValueError("prediction_scores.csv missing 'stock_id'. Re-run ablations after updating train_fusion.py.")

    preds["end_date"] = pd.to_datetime(preds["end_date"]).dt.normalize()

    print(f"Loading tabular samples from {args.tabular_samples}...")
    samples = pd.read_csv(args.tabular_samples)
    if "date" in samples.columns:
        samples["date"] = pd.to_datetime(samples["date"]).dt.normalize()
    elif "end_date" in samples.columns:
        samples["date"] = pd.to_datetime(samples["end_date"]).dt.normalize()
    else:
        raise ValueError("tabular_samples.csv must contain 'date' or 'end_date' column.")

    # Identify return columns
    stock_ret_col = next(
        (c for c in samples.columns if "future" in c and "return" in c and "index" not in c and "benchmark" not in c),
        None,
    )
    index_ret_col = next(
        (c for c in samples.columns if "future" in c and "return" in c and ("index" in c or "benchmark" in c)),
        None,
    )

    if args.use_y_proxy:
        print("WARNING: --use-y-proxy flag set. Using y_true outperformance proxy (not a real backtest).")
        stock_ret_col = "proxy_stock_return"
        index_ret_col = "proxy_index_return"
        samples[stock_ret_col] = samples.get("label", preds["y_true"]) * 0.01
        samples[index_ret_col] = 0.005
    elif not stock_ret_col or not index_ret_col:
        if args.raw_dir is None:
            raise ValueError(
                "tabular_samples.csv has no future_return columns and --raw-dir was not provided. "
                "Pass --raw-dir pointing to the directory with raw per-stock CSVs and NSEI.csv, "
                "or use --use-y-proxy to fall back to the classification-label proxy (not a real backtest)."
            )
        print(f"Computing real forward returns from raw CSVs in {args.raw_dir} (horizon={args.horizon_days}d)...")
        samples = _compute_forward_returns(samples, Path(args.raw_dir), args.horizon_days)
        stock_ret_col = "stock_future_return"
        index_ret_col = "index_future_return"
    else:
        print(f"Using existing return columns: stock={stock_ret_col}, index={index_ret_col}")

    # Merge predictions with samples
    merged = pd.merge(
        preds,
        samples[["stock_id", "date", stock_ret_col, index_ret_col]],
        left_on=["stock_id", "end_date"],
        right_on=["stock_id", "date"],
        how="inner",
    )

    if merged.empty:
        raise ValueError("No matching rows after merging predictions with tabular samples on stock_id + date.")

    print(f"Merged {len(merged)} rows covering {merged['end_date'].nunique()} rebalance dates.")

    # Backtest loop
    dates = sorted(merged["end_date"].unique())
    portfolio_returns: list[float] = []
    benchmark_returns: list[float] = []
    position_counts: list[int] = []

    for d in dates:
        day_data = merged[merged["end_date"] == d].dropna(subset=[stock_ret_col])
        if day_data.empty:
            continue
        top_k = day_data.nlargest(args.top_k, "y_prob")
        portfolio_returns.append(float(top_k[stock_ret_col].mean()))
        benchmark_returns.append(float(day_data[index_ret_col].dropna().iloc[0] if not day_data[index_ret_col].dropna().empty else 0.0))
        position_counts.append(len(top_k))

    results = pd.DataFrame(
        {
            "date": dates[: len(portfolio_returns)],
            "portfolio_return": portfolio_returns,
            "benchmark_return": benchmark_returns,
        }
    ).set_index("date")

    results["portfolio_cum"] = (1 + results["portfolio_return"].fillna(0)).cumprod()
    results["benchmark_cum"] = (1 + results["benchmark_return"].fillna(0)).cumprod()

    excess = results["portfolio_return"] - results["benchmark_return"]

    metrics = {
        "total_return_model": float(results["portfolio_cum"].iloc[-1] - 1),
        "total_return_benchmark": float(results["benchmark_cum"].iloc[-1] - 1),
        "trading_days": len(results),
        "rebalance_dates": len(dates),
        "avg_position_count": float(np.mean(position_counts)),
        "sharpe_ratio": _sharpe(excess),
        "max_drawdown_model": _max_drawdown(results["portfolio_cum"]),
        "note_sharpe": "Risk-free rate = 0, 252 trading days/year assumed",
        "return_source": "real_forward_returns" if not args.use_y_proxy else "y_proxy",
    }

    metrics_path = output_dir / "backtest_metrics.json"
    with open(metrics_path, "w") as f:
        json.dump(metrics, f, indent=2)

    print(f"\nMetrics saved to {metrics_path}")
    for k, v in metrics.items():
        if isinstance(v, float):
            print(f"  {k}: {v:.4f}")
        else:
            print(f"  {k}: {v}")

    # Plot
    plt.figure(figsize=(10, 6))
    plt.plot(results.index, results["portfolio_cum"], label=f"Top-{args.top_k} Portfolio", color="blue")
    plt.plot(results.index, results["benchmark_cum"], label="Benchmark (^NSEI)", color="gray", linestyle="--")
    plt.title("Cumulative Returns: Portfolio vs Benchmark")
    plt.xlabel("Date")
    plt.ylabel("Cumulative Growth (1.0 = baseline)")
    plt.legend()
    plt.grid(True, alpha=0.3)

    plot_path = output_dir / "backtest_curve.png"
    plt.savefig(plot_path, bbox_inches="tight")
    plt.close()
    print(f"Plot saved to {plot_path}")


if __name__ == "__main__":
    main()
